In [10]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(array1.ravel())
print(array1.flatten())

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(np.array_equal(arr1, arr2))

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

for arr_xy, name in [(x, 'x'), (y, 'y')]:
    vals, counts = np.unique(arr_xy, return_counts=True)
    max_val = vals[np.argmax(counts)]
    idxs = np.where(arr_xy == max_val)[0]
    print(f"Array {name}: Most frequent {max_val}, Indices {idxs}")

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(np.sum(gfg))
print(np.sum(gfg, axis=1))
print(np.sum(gfg, axis=0))

n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
print("Diagonal sum ", np.trace(n_array))
eig_vals, eig_vecs = np.linalg.eig(n_array)
print("Eigenvalues ", eig_vals)
print("Eigenvectors \n", eig_vecs)
print("Inverse \n", np.linalg.inv(n_array))
print("Determinant ", np.linalg.det(n_array))

p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
print("Multiplication:\n", np.dot(p, q))
print("Covariance:\n", np.cov(p, q))

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("Inner:\n", np.inner(x, y))
print("Outer:\n", np.outer(x, y))
print("Cartesian:\n", np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2))

array = np.array([[1, -2, 3], [-4, 5, -6]])
print("Absolute:\n", np.abs(array))
print("Percentiles column-wise:\n", np.percentile(array, [25, 50, 75], axis=0))
print("Percentiles row-wise:\n", np.percentile(array, [25, 50, 75], axis=1))
flat = array.flatten()
print("Mean:", np.mean(flat), "Median:", np.median(flat), "Std Dev:", np.std(flat))
print("Column-wise mean:", np.mean(array, axis=0))
print("Row-wise mean:", np.mean(array, axis=1))

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("Floor:", np.floor(a))
print("Ceil:", np.ceil(a))
print("Truncate:", np.trunc(a))
print("Round:", np.round(a))

array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted:", np.sort(array))
print("Indices sorted:", np.argsort(array))
print("4 smallest:", np.sort(array)[:4])
print("5 largest:", np.sort(array)[-5:])

array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print("Integers:", array[np.equal(np.mod(array, 1), 0)])
print("Floats:", array[np.not_equal(np.mod(array, 1), 0)])

import numpy as np
from PIL import Image

def img_to_array(path, save_array_path="saved_image.txt", save_shape_path="shape.npy"):
    img = Image.open(path)
    arr = np.array(img)

    if arr.ndim == 2:
        print("Image is Grayscale")
    elif arr.ndim == 3 and arr.shape[2] == 3:
        print("Image is RGB")

    np.savetxt(save_array_path, arr.reshape(-1), fmt='%d')
    np.save(save_shape_path, arr.shape)

def load_image_array(array_path="saved_image.txt", shape_path="shape.npy"):
    shape = tuple(np.load(shape_path))
    arr_flat = np.loadtxt(array_path, dtype=int)
    arr = arr_flat.reshape(shape)
    return arr

img_to_array("sample_image.jpg")
arr = load_image_array()
print("Loaded array shape:", arr.shape)

[5 4 6 3 2 1]
[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]
True
Array x: Most frequent 1, Indices [0 5 7 8 9]
Array y: Most frequent 1, Indices [0 1 2]
45
[[14]
 [16]
 [15]]
[[20  9 16]]
Diagonal sum  176
Eigenvalues  [98.16835147 28.097044   49.73460452]
Eigenvectors 
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse 
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant  137180.0000000001
Multiplication:
 [[16 19]
 [26 31]]
Covariance:
 [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
Inner:
 [[17 52]
 [13 62]]
Outer:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4